name: imgstore

channels:
  - conda-forge
  - defaults

dependencies:
  - conda-forge::ffmpeg=4

  - opencv=3

  - python-dateutil
  - pytz
  - tzlocal

  - h5py
  - pyyaml
  - numpy
  - pandas
  - bloscpack

  - pytest
  - pytest-cov
  - pytest-pep8

  - pip:
    - "--editable=./"
